apiVersion: v1
kind: ConfigMap
metadata:
  name: global-environments
data:
  KEYCLOAK_URL: "http://keycloak.keycloak:8080"
  KEYCLOAK_REALM: "master"
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"