apiVersion: v1
kind: ConfigMap
metadata:
  name: global-environments
data:
  KEYCLOAK_URL: "http://keycloak.keycloak:8080"
  KEYCLOAK_PUBLIC_URL: "http://keycloak.localtest.me:8080"
  KEYCLOAK_REALM: "master"
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KEYCLOAK_ENABLE_TOKEN_EXCHANGE: true
  KEYCLOAK_REGISTER_CLIENT: true
