# Copyright 2025 IBM Corp.
# Licensed under the Apache License, Version 2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kagenti-system

resources:
  - namespace.yaml
  - rbac.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - httproute.yaml

commonLabels:
  app.kubernetes.io/part-of: kagenti
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/kagenti/kagenti-backend
    newTag: latest
  - name: ghcr.io/kagenti/kagenti-ui
    newTag: latest
