# Copyright 2025 IBM Corp.
# Licensed under the Apache License, Version 2.0

apiVersion: v1
kind: Namespace
metadata:
  name: kagenti-system
  labels:
    app.kubernetes.io/name: kagenti
    app.kubernetes.io/component: ui
