secrets:
  # Your public Github User ID
  githubUser: ""
  # Your personal GitHub Token - required only if using ghcr.io as registry for builds
  githubToken: ""
  # Required as Ollama not yet available
  openaiApiKey: ""
  # not required until auth is enabled and slack demo agent is used
  slackBotToken: ""
  # not required until auth is enabled and slack demo agent is used
  adminSlackBotToken: ""
  # only required if using quay.io as registry to build and push images to
  quayUser: ""
  # only required if using quay.io as registry to build and push images to
  quayToken: ""
