apiVersion: v2
name: kagenti
description: A Helm chart for deploying the kagenti platform
type: application
version: 0.1.2
appVersion: "0.1.2"

dependencies:
- name: kagenti-operator-chart
  version: 0.2.0-alpha.19
  repository: oci://ghcr.io/kagenti/kagenti-operator
  condition: components.agentOperator.enabled
- name: kagenti-webhook-chart
  version: 0.1.0-alpha.9
  repository: oci://ghcr.io/kagenti/kagenti-extensions
  condition: components.platformWebhook.enabled
