{{- if and .Values.components.certManager.enabled .Values.openshift }}
{{- /* Skip Namespace if it already exists */}}
{{- if not (lookup "v1" "Namespace" "" .Values.certManager.namespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.certManager.namespace }}
  labels:
    {{- include "kagenti.labels" . | nindent 4 }}
{{- end }}
---
{{- /* Skip OperatorGroup if it already exists */}}
{{- if not (lookup "operators.coreos.com/v1" "OperatorGroup" .Values.certManager.namespace "openshift-cert-manager-operatorgroup") }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operatorgroup
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "kagenti.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - {{ .Values.certManager.namespace }}
{{- end }}
---
{{- /* Skip Subscription if cert-manager operator already exists */}}
{{- if not (lookup "operators.coreos.com/v1alpha1" "Subscription" .Values.certManager.namespace "openshift-cert-manager-operator") }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-cert-manager-operator.cert-manager-operator: ""
    {{- include "kagenti.labels" . | nindent 4 }}
  name: openshift-cert-manager-operator
  namespace: {{ .Values.certManager.namespace }}
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
{{- end }}

