{{- if and .Values.components.keycloak.enabled .Values.openshift }}
{{- /* Skip OperatorGroup if it already exists */}}
{{- if not (lookup "operators.coreos.com/v1" "OperatorGroup" .Values.keycloak.namespace "keycloak-operatorgroup") }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: keycloak-operatorgroup
  namespace: {{ .Values.keycloak.namespace }}
  labels:
    {{- include "kagenti.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - {{ .Values.keycloak.namespace }}
{{- end }}
---
{{- /* Skip Subscription if Keycloak/RHBK operator already exists */}}
{{- if not (lookup "operators.coreos.com/v1alpha1" "Subscription" .Values.keycloak.namespace "rhbk-operator") }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  namespace: {{ .Values.keycloak.namespace }}
  labels:
    operators.coreos.com/servicemeshoperator3.openshift-operators: ""
    {{- include "kagenti.labels" . | nindent 4 }}
spec:
  channel: stable-v26.2
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
{{- end }}
