{{- if and .Values.components.kiali.enabled (not .Values.openshift) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: {{ .Values.istio.namespace }}
  labels:
    app: kiali
    {{- include "kagenti.labels" . | nindent 4 }}
    app.kubernetes.io/component: kiali
spec:
  parentRefs:
    - name: http
      namespace: {{ .Release.Namespace }}
  hostnames:
    - kiali.{{ .Values.domain | default "localtest.me" }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kiali
          port: 20001
{{- end }}