{{- if and .Values.components.tekton.enabled .Values.openshift }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
    {{- include "kagenti.labels" . | nindent 4 }}
spec:
  channel: pipelines-1.14
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
