name: TestBuild

on:
  # run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  REPO: kagenti/kagenti
  CHARTS_PATH: ./charts

jobs:
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions to write packages
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image_config:
          - name: ui-v2
            path: ./kagenti
          - name: backend
            path: ./kagenti    

    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to the GitHub Container Registry (ghcr.io)
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push ${{ matrix.image_config.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image_config.path }}/${{ matrix.image_config.name }}
          file: ${{ matrix.image_config.path }}/${{ matrix.image_config.name }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ matrix.image_config.name }}:latest
          labels: test